version: '3.8'

services:
  mysql:
    image: mysql:5
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: r
      MYSQL_DATABASE: malware_site
      MYSQL_USER: toor
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: