apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: felpsxill/malware-app:frontend-latest
        imagePullPolicy: Always  # Garante que a imagem seja sempre puxada do registro
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred  # Use se o registro precisar de autenticação
