apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: felpsxill/malware-app:backend-latest
        imagePullPolicy: Always  # Garante que a imagem seja sempre puxada
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"  
        - name: DB_USER
          value: "toor"
        - name: DB_PASS
          value: "root"
        - name: DB_NAME
          value: "malware_site"
      imagePullSecrets:
      - name: regcred  # Se você precisar de autenticação
